author:
  name: "Гульназ"
  surname: "Хабибуллина"
  nickname: "Shaton"
  socials:
    twitter: "-"
    google_plus: "-"
    vkontakte: "-"
    odnoklassniki: "-"
    facebook: "-"
    livejournal: "-"
    blogger: "-"
    email: "-"

url: "http://gulnazshaton.ru/"
github: "https://github.com/GulnazShaton/GulnazShaton.github.io"
description: "Уютное место для моих мыслей"
start_time: 2015-12-25 18:00:00 +0300

sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: false
highlighter: rouge
timezone: Russia/Moscow

permalink: :categories/:title/

defaults:
  -
    scope:
      path: _posts/blog
      type: posts
    values:
      category: blog
      layout: post
  -
    scope:
      path: _posts/portfolio
      type: posts
    values:
      category: portfolio
      layout: post
  -
    scope:
      path: _posts/notes
      type: posts
    values:
      category: notes
      layout: post

exclude: ['_site/', '.sass-cache/', 'node_modules/', 'gulpfile.js', 'package.json', 'CNAME', 'README.md']
